### ISSUE TITLE
Done : Raccourcir le décompte

### ISSUE THREAD

**Issue by PandalionCheese** [PandalionCheese/Cheese#2]
https://github.com/PandalionCheese/Cheese/blob/master/src/App.js
3 secondes + Cheese! (1sec) + attente avant déclenchement : trop long

**Comment by HadrienPierart** [comment]
Le temps d'attente avant le déclenchement est incompressible a priori car
il faut le temps que l'appareil fasse la mise au point.  Donc on a pas le
contrôle a priori

Le mar. 27 nov. 2018 à 12:21, PandalionCheese <notifications@github.com> a
écrit :
